### ISSUE TITLE
Embed popup design

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#1]
This is the design of the embed popup. 

![webdesign_embedpopup](https://cloud.githubusercontent.com/assets/3542255/8228818/23f3ad14-15b2-11e5-854e-9967f9bfabed.png)

Can you work with these designs?

**Comment by tomkr** [comment]
@Taskamp That looks good. What exactly does the "Toon preview" toggle do, display or hide the image below? And is there still an option for OEmbed instead of iFrame?

**Comment by mzeinstra** [comment]
@tomkr There is an OEmbed option available, if #2 is followed it should be the url of the page that shows this image. 

See http://embedhawk.klokantech.com/_2020720_DR_29fcd5ee955ffee85f0a26d0063986da as an example. It has code for oEmbed to http://embedhawk.klokantech.com/oembed?url=http%3A//embedhawk.klokantech.com/_2020720_DR_29fcd5ee955ffee85f0a26d0063986da/0&format=json

**Comment by Taskamp** [comment]
You can remove the preview from the embed popup.

**Comment by tomkr** [comment]
Preview has been removed. I think this one can be closed, as the embedding itself is discussed elsewhere.
