### ISSUE TITLE
CloudSearch implemented

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#11]
Cloud Search implemented contains three subtasks. basic search and facetted search should be available.

- [x] Cloudsearch available for full text search
- [x] Cloudsearch available for facet search (see https://github.com/klokantech/hawk/issues/31 for facets)

Next to that it should be possible to filter on Creative Commons licenses. (ticket to be created)

**Comment by tomkr** [comment]
The search now allows [lucene syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html). For instance specific fields can be accessed with field:search. I assume this will be good enough at this stage.

**Comment by mzeinstra** [comment]
This will work for now, Not sure if it works as specified as #7 is needed.
