### ISSUE TITLE
Implement Creative Commons licenses as advanced filter for search

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#12]
The metadata set contains creative commons licenses. These should be filterable.

There are over 500 different license possibilities, due to different versions and porting to different jurisdictions. That is why I suggest using wildcards here. Please be aware of the trailing slashes to avoid false positives. Also be aware that the URLs can be in uppercase but are usually in lowercase.

These options should be:

* No filter
* Freely reusable 
* Non commercial use only

# Freely reusable 
This means searching for 
* https://creativecommons.org/publicdomain/mark/1.0/
* https://creativecommons.org/publicdomain/zero/1.0/
* BY
* BY-SA
* BY-ND

Suggest you use wildcards (OR):
* "\*creativecommons.org/publicdomain/\*"
* \*BY/\*
* \*BY-SA/\*

Trailing slashes prevent false positives of more restrictive licenses.

# Non commercial use only
These include:
* BY-NC
* BY-NC-SA

suggest you use wildcards (OR):
* \*BY-NC/\*
* \*BY-NC_SA/\*

Trailing slashes prevent false positives of more restrictive licenses.

**Comment by mzeinstra** [comment]
Simplified the options to be developed.

**Comment by tomkr** [comment]
@mzeinstra Initial version is done, could you test to see where it is not working as intended.

**Comment by mzeinstra** [comment]
Seems ok so far, proper testing could only be done after #7 is finished.

**Comment by Taskamp** [comment]
No need to include 'no filter', 
It's enough to have 'freely reusable' and 'non commercial use only' is enough

**Comment by mzeinstra** [comment]
See #52
