### ISSUE TITLE
Quickembed in search results

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#13]
On this design page we have a quick embed button:
![hawk_webdesign_search_result_embed](https://cloud.githubusercontent.com/assets/5627431/8287087/c921530a-190d-11e5-8069-6c9bd91cae71.jpg)

Hovering over an image result shows you the embed button. Clicking that button does a copy of the iFrame Embed code of that image.

This is low priority.

**Comment by tomkr** [comment]
This is possible, but it will only work for the iFrame embedding, since you can't crop here.
