### ISSUE TITLE
Icons appear when hovering over

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#15]
When the user embeds in iFrame, the whole page is copied. The icons (zoom, rotate, metadata etc) should therefore ideally not appear directly on the image (as is indicated in the design we sent you) but only when the user hovers over. Alternatively, there can be one small icon (like a menu bar), and when the user clicks on it, all the other icons pop out. This way, there is a nicer view of the image. 

![screen shot 2015-06-23 at 10 22 15](https://cloud.githubusercontent.com/assets/3542255/8301825/c1e84da8-1991-11e5-98a4-7e49dc5a1776.png)

**Comment by tomkr** [comment]
This is implemented as part of the viewer code and should show up there.
