### ISSUE TITLE
Text box 'embed this image' should be in English

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#16]
Unclear instructions on our side. The text box 'dit beeld embedden' should be in English.

![screen shot 2015-06-23 at 11 30 28](https://cloud.githubusercontent.com/assets/3542255/8303053/617dc98e-199b-11e5-9434-456752f43bee.png)

The text should be:
'Embed this image'
'Copy the HTML code below to your website or blog.'
'Click here for more information'

'Copy' (button)
'Show preview'

**Comment by tomkr** [comment]
@Taskamp @mzeinstra Texts have been updated.
