### ISSUE TITLE
Website needs Google Analytics

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#17]
Website needs Google Analytics. I believe this will not be a problem for most pages, it can become a problem for the large viewer page, right?

Tracking code: UA-64494530-1

**Comment by tomkr** [comment]
What do you want to measure for the viewer page? I can setup GA for the search result page, but then it won't measure embeds. I guess you want that as well, right?

**Comment by tomkr** [comment]
@mzeinstra Could you generate the whole embed code? I can't sign in to you google analytics account and the ones I have are really old.

**Comment by mzeinstra** [comment]
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64494530-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by tomkr** [comment]
You should be seeing events start to come in.

**Comment by tomkr** [comment]
* [ ] Check that detail page also has GA.
