### ISSUE TITLE
A single display of viewer design for Klokan's iFrame and display of content here.

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#2]
On https://github.com/klokantech/hawk/blob/master/embed/app/templates/iframe_openseadragon_inline.html
you will find the code for the iFrame embedding of the IIIF service of Embedr.eu. We want this the same as the templates that you've already been working on. 

Klokan suggested you use javascript to determine if the iFrame is loaded as the main window, that way you could develop the entire page instead of embedding the iframe below a menubar. You could use something like if(self==top) and if(parent==top) to hide the menubar when the page is loaded as an iframe.

Please do a pull request when this work is done.

**Comment by mzeinstra** [comment]
Implementation of this openseadragon can be found on: http://embedhawk.klokantech.com/_2020720_DR_29fcd5ee955ffee85f0a26d0063986da

**Comment by tomkr** [comment]
As discussed it might be easier to put the iframe below the menubar after all and implement the viewer on klokantech side.

**Comment by tomkr** [comment]
A PR for this is pending at Klokantech.

**Comment by tomkr** [comment]
Viewer is PR'd into klokantechs pages now, so this should be done. Future changes will be done in the same way.
