### ISSUE TITLE
JSON embedr link should not be relative protocol URL

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#21]
As we have no HTTPS we should not allow iFrames with a relative protocol URL, that might give security issues,

**Comment by tomkr** [comment]
I don't know the exact url that is needed in the embed iframe, so I put in a placeholder for now. If you have exactly what needs to be put in there, please let me know.

**Comment by mzeinstra** [comment]
Right, closing this ticket to open a ticket on a definitive iFrame code.
