### ISSUE TITLE
iFrame embed code

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#22]
I would like to something like:
```
<div class="embdrWrapper" style="position: relative; padding-bottom: 124%; padding-top: 0px; height: 0;">
    <iframe style="border: 0; position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="http://media.embedr.eu/_2021638_dispatcher_aspx_action_search_database_ChoiceCollect_search_priref_4616">
        Your browser doesn't support iFrames.
    </iframe>
</div>
```

and have a relative padding-bottom to indicate the width / height percentage. This results in a div that has the maximum width of its container and allow that to fill in the image as large as possible. Essentially displaying it in a full screen way.

I see in https://github.com/klokantech/hawk/issues/43 that width and height will become available in CloudSearch.

**Comment by klokan** [comment]
What is suggested here is quite ugly. You should not really need to use width / height on the web site - it just suggest you try to do something in a wrong way.
For square thumbnails there is an URL syntax - if we upgrade the iiifserver.
Iframe bigger then a visible window is causing downloading of tiles which are never displayed and allocating extra canvas space (memory) in browser.

Why not to adjust the javascript code of the OpenSeaDragon with one extra option instead?(https://github.com/openseadragon/openseadragon/pull/474)
Also, the viewer would be better to run on media.embedr.eu - klokantech/hawk#28

**Comment by mzeinstra** [comment]
@klokan Sure I see your point, this should not be used on embedr.eu to present the viewer. 

I am not sure if you thought that this would replace the viewer on embedr.eu. it should not. This issue is about what embedcode should be presented to users of embedr when wanting to embed. a viewer on their own sites.

Now, I am not a front-ender and this issues was merely an implementation how I would hack this together. What I require is an embed code that embed the highest width and height allowed on a third party site, without having to manually select a custom width and height.

**Comment by klokan** [comment]
Embedding code must be minimal and straightforward - as on YouTube for example:
`<iframe width="560" height="315" src="https://www.youtube.com/embed/cqQrWWpcT0I" frameborder="0" allowfullscreen></iframe>`
People should be able to change width and height and that's it...

This change of behaviour should happen on the media.ember.eu viewer - in JavaScript / HTML / CSS - so as part of klokantech/hawk#28 modified template.
The mentioned `homeFillsViewer:true` in OpenSeaDragon component may do what @mzeinstra want's here probably - otherwise it can be implemented in JavaScript directly by @tomkr. The template has the information about the width / height of image in JavaScript already. There is no need to access it from CloudSearch).

**Comment by mzeinstra** [comment]
Ah I see, let's see what Tom will develop. I am of course al for a minimal embed code and let as much as possible be solved from within the iframe.

**Comment by mzeinstra** [comment]
@tomkr I've made mockup of the different embed possibilities.

What I want is an iframe embedcode that looks like the last implementation and to have that implementation iframe embed code as simple as possible.

http://dev.embedr.eu/hello-vienna/#/

If that is not doable, I will be ok with the more complicated embed code described above.

**Comment by tomkr** [comment]
I've experimented a little on the page and it looks like the super simple version, which sets just a height, works quite ok. Check it out at the bottom of http://dev.embedr.eu/hello-vienna/#/.

This would make the code:
`<iframe height="315" src="http://media.embedr.eu/_2058701_File_Lekande_uttrar__Kent_Ullberg_1997__2__JPG"" frameborder="0" allowfullscreen></iframe>`

Is this ok for now?

**Comment by mzeinstra** [comment]
It does not scale up to the max available space, which I think is a shame and waste of HQ imagery. I'd rather see a method that fills out the maximum width of its enclosing container and adjusts its size accordingly. I believe this is possible with javascript.

**Comment by tomkr** [comment]
@mzeinstra The top embed url is what we settled on now right? I will remove the lower one and then this one should be finished.

**Comment by mzeinstra** [comment]
Yes that is correct.

**Comment by Taskamp** [comment]
Then I will ask our designer to design the embed box again.

**Comment by klokan** [comment]
The `padding-bottom: 84.58336273195512%` in a div around iframe is extremely ugly hack - very visible to anybody who will use embedr. This is a serious problem - not fixed yet @mzeinstra 
For iframe embedding you don't need any paddings and wrapping divs... have a look at iframe embed of youtube for example.

**Comment by mzeinstra** [comment]
@klokan, how would you make a full width embed without padding? 

The embed code needs to have the following functionality
* it needs to fill out the width of its container
* it needs to keep the aspect ratio of the image, to not have white space around the image.

**Comment by klokan** [comment]
By modification of the JavaScript code of viewer at http://media.embedr.eu/Rijksmuseum_SK-C-5

There is no need for wrapper div and padding in the user visible HTML embed code.
The viewer knows width / height, zoom levels, can easily detect it is inside of iframe and behave as you define.

**Comment by mzeinstra** [comment]
We'll look into it further. It is a known solution that is used throughout the internet though: for example: https://iframely.com/embed/https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D4pCNJKGhQXM
