### ISSUE TITLE
visual tweaks to front-page

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#27]
The following dutch feedback was received from our designer:

- [x] advanced search moet rechts uitlijnen met zoekbox (steekt nu iets uit), font size: 14px.
- [x] hoofdnavigatie moet aan bovenkant uitlijnen met bovenkant logo (stokjes van b en d).
- [x] onderkant zoekbox moet uitlijnen met onderkant introtekstjes (regel 3 'image embedding').
- [x] 'search' in zoekbox moet Raleway 18px zijn en is het mogelijk om een grote cursor weer te geven voor 'search' zoals in het design?
- [x] logo/introtekst/navigatie moeten subtiele dropshadow krijgen tbv leesbaarheid op lichte achtergronden.

Concering advanced search dropdown
- [x] font-size moet 14px zijn en meer afstand tussen radiobutton en tekst en verticaal daarmee uitlijnen (tekst staat nu te hoog). 
- [ ] Is het niet mogelijk om witte rondjes met witte bolletjes te maken? 
- [x] Er moet 6px tussenruimte tussen de zoekbox en de dropdown. 
- [x] Transparancy achtergond dropdown op 0.8 zetten (donkerder maken). 
- [x] Regelafstand iets groter maken.

**Comment by tomkr** [comment]
* Grotere cursor kan in elk geval niet met simpele styling.
* Radio buttons aanpassen is waarschijnlijk met afbeeldingen, maar dat is wel wat extra werk.

**Comment by mookl** [comment]
* grotere cursor snap ik, maar font kan dus ook niet aangepast worden?
* radio buttons is prima zo.
* advanced search: uitlijning is goed, maar er is iets mis met de Raleway Regular, die ziet er veel te vet uit (kan het niet in de code vinden, dus er is iets anders aan de hand, in de vorige versie klopte het font wel, behalve de size). De Regular ziet eruit als Bold. Het gekke is dat ik het niet terug kan vinden in de code en ook Whatfont zegt dat het regular is, maar ik weet zeker dat het dat niet is en eerder dus wel.
* 'search' in zoekbox klopt nog niet (is Helvetica Neue, geen Raleway).
* over de dropshadows: beter, maar alphawaarde op 0.7 zetten (iets subtielere shadow).
* advanced search dropdown: mooi, alleen weer dat Raleway-probleem (te bold).

**Comment by mzeinstra** [comment]
Laatste opmerkingen van de designer:

- [ ] meer afstand tussen de zoekbox en de navigatie
- [ ] bovenkant zoekbox lijnt met bovenkant introtekst
- [ ] logo moet 56px ipv 50px
- [ ] introtekst moet 18px / 24px zijn ipv 14 / 20
- [ ] Search’ moet met kleine letter beginnen.

Hier zijn wat guidelines die duidelijk maken hoe een en ander uitgelijnd moet zijn.
![pasted_image_at_2015_07_14_03_35_pm](https://cloud.githubusercontent.com/assets/5627431/8695473/7b8541f8-2ae5-11e5-904a-b102fdf723a5.png)

**Comment by Taskamp** [comment]
Nog wat visual tweaks:

- [ ] Logo (Embedr image embedding done right) moet worden gefinetuned, volg het design zoals de designer het heeft aangeleverd. 
- [ ] "Search" in de zoekbalk moet "search" worden, dus met een kleine letter. 
- [ ] Nadat je een foto hebt geselecteerd, zorg dat de icoontjes zijn uitgelijnd met het logo. Nu staan de icoontjes te veel naar links. De meest linkse moet direct onder het logo staan.
- [ ] De embed box moet worden uitgelijnd met het logo. Hij moet direct onder het logo staan. Dus precies onder elkaar aan de linkerkant, evenals de icoontjes (zie comment hierboven). 
- [ ] Nadat je een foto hebt geselecteerd, zorg dat de foto gecentreerder wordt. Nu valt de bovenkant precies onder de zwarte balk. Hij moet iets naar beneden.

**Comment by tomkr** [comment]
I've added the default viewer (dev.embedr.eu/viewer/Clark.html) to the site now. This means we won't have to do PRs for things that are not yet done. But you can see the current detail view in the site now, but it'll only have one image.

**Comment by Taskamp** [comment]
One final detail, the radio buttons in the Advanced search dropdown box are blue when ticked, and should be white. 

See here what it's like at the moment:

![screen shot 2015-09-16 at 17 33 15](https://cloud.githubusercontent.com/assets/3542255/9909551/0c3360d8-5c99-11e5-8e77-7e6d6ecb4146.png)

It should be:

![screen shot 2015-09-16 at 17 09 36](https://cloud.githubusercontent.com/assets/3542255/9909560/12903604-5c99-11e5-96e7-f0e7e0675d77.png)

**Comment by mzeinstra** [comment]
Let's make a separate ticket of this.
