### ISSUE TITLE
Visual tweaks search page

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#29]
- [x] zoekoverzicht: donkere layer op 0.8 zetten ipv 0.6 (donkerder maken dus).
- [x] zoekoverzicht: thumbs moeten 204x204px zijn, aantal op een rij afhankelijk van de breedte van het window en links en rechts altijd een margin van minimaal de afstand tussen logo en windowrand in stand houden.  Ook hier afstand tussen zoekbox en thumbs 82px (zoals bij tekstpagina).
- [x] zoekoverzicht: titel onder thumbs moet Ubuntu font-size: 12px / line-height: 14px zijn (stond verkeerd in het design, excuus).

**Comment by tomkr** [comment]
The issue with the search is that with a flexible amount of columns it's hard to center it. It'll probably need some kind of javascript solution. Would it be ok to fix the results to 5 or 6 columns for now? We will look at a solution in a next release?

**Comment by mzeinstra** [comment]
That would be ok.

**Comment by mookl** [comment]
* beter, maar breakpoint/margins left/right op 40px zetten (gelijk aan afstand logo tot window border). Max. 6 kolommen is prima.
* titels onder thumbs zijn niet regular en nog te groot

**Comment by mzeinstra** [comment]
- [ ] advanced search link op thumbnailoverzichtpagina is niet leesbaar, kan je die daar wit maken ipv zwart als je de achtergrond donker maakt?

![screen shot 2015-07-15 at 11 37 14](https://cloud.githubusercontent.com/assets/5627431/8695586/2b02fb20-2ae6-11e5-910f-bb804a086c0f.png)

**Comment by tomkr** [comment]
Is it an option to make it white by default? The advanced search button and the overlay are actually different layers, so it's harder to make them change off each other than it might seem.

**Comment by mzeinstra** [comment]
That is ok.
