### ISSUE TITLE
Visual tweaks viewer

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#30]
- [x] embed-popup: titel moet zijn Raleway Extrabold 24px / line-height: 30px. 
- [x] P-tekst moet Ubuntu 24px / line-height: 30px zijn. 
- [x] Links moeten zwart en underlined zijn. 
- [x] 'Copy' moet met kleine beginletter en padding-left/right: 8px.
- [x] embed-popup: afbeelding close-kruisje doet het niet en moet rechtsboven in de hoek.

**Comment by tomkr** [comment]
Live on dev.embedr.

**Comment by mookl** [comment]
* embed-popup: geen Extrabold gedaan (maar bold) en 'copy' moet gecentreerd in de button.

**Comment by tomkr** [comment]
De afbeelding met het witte kruisje kon ik in de psd niet zo snel vinden. Is hij los beschikbaar. Andere punten heb ik aangepast.

**Comment by mookl** [comment]
Hoi Tom, hier is het plaatje: https://www.dropbox.com/s/ugujsnujj4ql29v/close_cross.png?dl=0
Zijn er al afspraken gemaakt over hidpi-afbeeldingen (voor retina-schermen)? Ik kan al je slices voor je vergroten naar 200% als je wilt.
