### ISSUE TITLE
visual tweak navigation

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#31]
- [x] hoogte moet 41px zijn en geen grijze rand om de foto. 
- [x] embedr-logo moet font-size:27px zijn. 
- [x] Navigatie moet font-size 18px zijn ipv 16. 
- [x] Zoekbox moet 30px hoog zijn. 
- [x] Kleinere versie van vergrootglas gebruiken en iets meer ruimte tussen zoekbox en vergrootglas (zie design).
- [x] Advanced search moet font-size: 13px zijn.

**Comment by tomkr** [comment]
Live on dev.embedr.

**Comment by mookl** [comment]
* advanced search is nog te vet, font klopt niet (is niet regular, ook al staat dat wel in de code), vergelijk met: http://www.fontsquirrel.com/fonts/raleway (site wide probleem, dat eerder wel oke was).

**Comment by tomkr** [comment]
Dit heb ik aangepast, was een issue met de fonts inladen.

**Comment by mookl** [comment]
Oke, nu nog het juiste font op alle plekken en de juiste font sizes en line heights en font weights.

**Comment by mookl** [comment]
Ik bedoel dus: https://github.com/tomkr/embedr/issues/28
