### ISSUE TITLE
Content pages

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#32]
There will probably be only 2 main headings for the content pages with respectively 3 and 1 subheadings. 

So the content page will look like this:
- About
           - Collection
           - How to embed
           - Technology
- Contact
           - Kennisland

We might change it and add Kennisland to one of the subheadings under 'About'

**Comment by Taskamp** [comment]
Our designer will come back to us with a design in the beginning of next week. 

The front page will have 3 nav's: About, How to embed and contact.
The rest will pop up in some sort of menu after the user has navigated to one of the headings. So there wil be no drop-down menu.

I will share the design with you asps

**Comment by tomkr** [comment]
Are these designs available yet?

**Comment by Taskamp** [comment]
Not yet. Our designer is currently out of office until this upcoming Monday. I noted it down already for that day. Will come asps.

**Comment by Taskamp** [comment]
I will send you the designs next Tuesday. Sorry for the delay, our designer is really busy after his holidays

**Comment by mookl** [comment]
Added: subnavigation on textpages. Maarten said: link them to new pages instead of to anchors on the same page (due to the length of the page).

Font: Raleway size 18 / line-height 18

![embedr_subnavigation](https://cloud.githubusercontent.com/assets/13234593/9327862/50d0f75c-45a4-11e5-8918-46795516f28e.jpg)

**Comment by tomkr** [comment]
The content pages should now work on dev.embedr.eu. Perhaps you could start filling some of them, so that I have some content to work with.

**Comment by mzeinstra** [comment]
Menu:
* About
* How to Embed
* Contact

**Comment by Taskamp** [comment]
Definitief menu:

About
       The collection
       Technology
       Attribution
How to embed
Contact
      Kennisland

3 main menus (zoals het nu al is). 
About heeft 3 sub's en contact heeft 1 sub.

**Comment by Taskamp** [comment]
Alle pages zijn aangemaakt in WP

**Comment by tomkr** [comment]
The submenu can now be seen at http://dev.embedr.eu/content/about/. It uses subpages defined in Wordpress so that each parent page has its own submenu.
