### ISSUE TITLE
Searching and selecting image from a WP content page give strange effects.

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#33]
![screen shot 2015-07-08 at 9 28 58](https://cloud.githubusercontent.com/assets/5627431/8565215/c812a7aa-2553-11e5-8eb0-47af0783769a.png)

There is text hovering above the image and you can still scroll the page. We should revert to the home page when searching from a content page.

**Comment by tomkr** [comment]
I've been working on restructuring the integration with Wordpress. This has caused the pages to stop working at the moment. This is something we need to discuss.

**Comment by tomkr** [comment]
This should be fixed. Wordpress content pages should be created as subpages under a /content page.
