### ISSUE TITLE
Add oEmbed to viewer on embedr.eu

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#35]
As the metatags are not available from within the iFrame to the embedded link please add the oEmbed code to the its parent window. 

So if go to: http://dev.embedr.eu/#/Canaletto_I_058_jpg

I want to see the same metadata as http://media.embedr.eu/Canaletto_I_058_jpg

In this case I believe it is these values.

```
    <meta name="google" value="notranslate">

	<meta name="dc:title" content="Vienna from Belvedere"/>
	<meta name="dc:creator" content="Bernardo Bellotto"/>
	<meta name="dc:source" content=""/>
	<meta name="dc:publisher" content="Kunsthistorisches Museum Wien"/>
	<meta name="dc:rights" content="https://creativecommons.org/publicdomain/mark/1.0/"/>
	<meta name="dc:description" content="1758"/>

    <link rel="alternate" type="application/json+oembed" href="http://media.embedr.eu/oembed?url=http%3A//media.embedr.eu/Canaletto_I_058_jpg/0&format=json" title="Vienna from Belvedere oEmbed Profile" />
	<link rel="alternate" type="text/xml+oembed" href="http://media.embedr.eu/oembed?url=http%3A//media.embedr.eu/Canaletto_I_058_jpg/0&format=xml" title="Vienna from Belvedere oEmbed Profile" />

    <title>Vienna from Belvedere</title>
```

This does not always seem to work on Facebook, if you can add OpenGraph, that would be great ;)

**Comment by tomkr** [comment]
@mzeinstra Since the database is not available in the search result page, I can fetch it from the search api, but that seems less than ideal. You have a widget for oembed right? I'm curious what happens when we put the current detail page in that, could you share it?

**Comment by tomkr** [comment]
Data from: http://media.embedr.eu/Rijksmuseum_SK-C-5/manifest.json

**Comment by tomkr** [comment]
http://dev.embedr.eu/Rijksmuseum_SK-C-5/ should be embeddable now.

**Comment by mzeinstra** [comment]
Your media player as 2 href tags in the alt. links. The first one probably needs to be removed.

**Comment by tomkr** [comment]
Should be fixed now.

**Comment by mzeinstra** [comment]
Checked, worked
