### ISSUE TITLE
Wordpress messes with viewer

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#37]
On http://dev.embedr.eu/about/#/_90402_RP_P_2003_48 we have some nice effects of Wordpress messing with our viewer:

![screen shot 2015-07-14 at 17 54 16](https://cloud.githubusercontent.com/assets/5627431/8677804/7c044afa-2a51-11e5-9663-566f8e6b5712.png)

**Comment by tomkr** [comment]
This is probably a duplicate of #33.

**Comment by mzeinstra** [comment]
Yes, it is.
