### ISSUE TITLE
Add rotation functionality

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#4]
Develop the functionality to rotate the image. 

There are 4 rotation options supported by IIIF: 0, 90, 180 and 370.

Rotation is designated by this icon:
![screen shot 2015-06-22 at 15 38 30](https://cloud.githubusercontent.com/assets/3542255/8283059/289ed712-18f5-11e5-9234-c1bf0e6e90a1.png)

**Comment by mzeinstra** [comment]
Rotation is available in OpenSeaDragon: https://openseadragon.github.io/docs/OpenSeadragon.html#Options
