### ISSUE TITLE
metadata overlay needs to be opaque instead of transparant

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#40]
The overlay of the metadata in the bottom of the viewer needs to remain opaque when resized. Not semi transparent like the image below.

![screen shot 2015-07-15 at 11 43 26](https://cloud.githubusercontent.com/assets/5627431/8695670/ca3ab494-2ae6-11e5-9c0c-e01fb04b0023.png)

**Comment by tomkr** [comment]
This should be fixed already.
