### ISSUE TITLE
Upgrade to OpenSeaDragon 2.0

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#41]
We are using OpenSeaDragon, it might be interesting to upgrade to 2.0. This also something that KlokanTech suggested.

**Comment by tomkr** [comment]
OpenSeaDragon 2.0 is already being used.

**Comment by tomkr** [comment]
I noticed now that while I personally include OSD 2, I'm using the one supplied by media.embedr.eu. Is it better to serve my own 2.0?

**Comment by mzeinstra** [comment]
I believe it is better to use OSD 2.0 so that would entail an pull request to Klokan right?

**Comment by tomkr** [comment]
I can't easily change their OSD with a PR, but I can package my own version of OSD, which might be better anyway
