### ISSUE TITLE
Last search item is still vaguely on the background when you do a new search query

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#46]
![screen shot 2015-08-04 at 17 40 15](https://cloud.githubusercontent.com/assets/3542255/9065147/47292ef6-3ad0-11e5-8f7f-5c0a83ba884e.png)

This should be black. 

The same goes for the first query. In that case, the background is still vaguely visible. This should be black.

![screen shot 2015-08-04 at 17 44 36](https://cloud.githubusercontent.com/assets/3542255/9065210/9260c3fc-3ad0-11e5-8816-850b1748a3fb.png)

**Comment by tomkr** [comment]
It's the same way in the designs, I believe.

**Comment by mzeinstra** [comment]
Won't fix is in original designs.
