### ISSUE TITLE
Design Tweak Embed pop up

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#48]
Er zijn nog enkele lichte aanpassinge aan de pop ups in de player. Zie foto

![embedr_embed](https://cloud.githubusercontent.com/assets/5627431/9330594/927df7e8-45ba-11e5-9cc5-7f7045d0944c.jpg)

Je ziet dat de fonts o.a. zijn aangepast. Deze zijn nu:
Font title: Raleway Extrabold 24px
Font body: Ubuntu regular 18px / line-height: 24px
Font copy button: Raleway 14 px

**Comment by Taskamp** [comment]
Small correction: after 'Copy the code below.' only 1 dot/period instead of 2.

**Comment by mookl** [comment]
I accidentally exported a badly aligned design (buttons-logo-embedbox). Here is the updated correct version.
![embedr_embed_aligned](https://cloud.githubusercontent.com/assets/13234593/9492033/245e21e4-4bf4-11e5-9cf4-9fbd55197cf5.jpg)

**Comment by Taskamp** [comment]
Here's some further information on the proportions:

![embedr design](https://cloud.githubusercontent.com/assets/3542255/9603678/a74d1b1a-50b2-11e5-8cf4-9c093e666863.png)

The logo, the first icon and the pop-up box are outlined on the same level.

**Comment by Taskamp** [comment]
This is not the final version yet, but it might help you out at the moment. 

![embedr_embed_08092015 1](https://cloud.githubusercontent.com/assets/3542255/9756029/283a7978-56d7-11e5-99d4-1104a7c00b06.jpg)

Instead of "Click here for more information" it should be "Click here to learn more about embedding"

**Comment by Taskamp** [comment]
Here's the final design of the embed pop-up box, in accordance with the changes that we have added to the issues on github yesterday.

![embedr_embed_11092015](https://cloud.githubusercontent.com/assets/3542255/9817544/f1b6af9c-58a3-11e5-9eef-d2121f5cb338.jpg)

You see two question marks after zoomable image and static image. These are mouseovers. 

The texts in the mouseover should be:

Zoomable image: "A zoomable image is one that you can zoom, pan and rotate. If you embed a zoomable image, it will look precisely the same on your blog as on embedr.eu"

Static image: "A static image is a visual image that you cannot move. If you embed a static image on your website or blog, you will have an image that you can no longer zoom, pan and rotate"

One small deviation from the design: there should be no dash between HTML and code.

I will send you the icons by mail.

**Comment by Taskamp** [comment]
In alignment with the change in design above, there are also some minor changes in the design of the region embed popup.

![screen shot 2015-09-11 at 17 22 13](https://cloud.githubusercontent.com/assets/3542255/9818591/afd3c3e8-58a9-11e5-8451-146870fe5256.png)

"Click here for more information" should be "More information about embedding"

**Comment by Taskamp** [comment]
Here's the design for the region embed.

![hawk_webdesign_selection_embed](https://cloud.githubusercontent.com/assets/3542255/9843547/9b32c1c8-5abb-11e5-98ef-44da62a6c47e.jpg)

Some modifications:
1. in plaats van ‘rotation’ moet er staan "The maximum width and height are 2056 pixels’" 
2. “more information” moet “More information about embedding “ 
3. De scroll moet er uit 
4. Het kruisje moet een kruisje in een rondje zijn (al zijn die laatste 2 zo aangepast, kunnen we ook rechtstreeks aan tom doorgeven)

**Comment by Taskamp** [comment]
Here's the final design of the region selection popup

![embedr_crop](https://cloud.githubusercontent.com/assets/3542255/9904581/3271be9e-5c7f-11e5-895b-a08fde511e55.jpg)

**Comment by Taskamp** [comment]
It's starting to look good!
A few small details:

There should be a mouseover after 'Adjust the size of the image' 
The text should be: "The maximum width and height are 2056" instead of 'The width and height have a maximum of 2056 pixels;

**Comment by Taskamp** [comment]
Also the normal embed popup looks good. The tickbox is still missing though, I assume because there is no option for a static embed using iFrame yet. Just implement it as soon as this function is working.

**Comment by mzeinstra** [comment]
Closing this issues, the additional tick box needs to be its own issue.
