### ISSUE TITLE
Select a region and embed only that region

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#5]
IIIF supports the selection of a region, and generate an embeddable link of this region only.

Ideally the region is selected by means of a bounding box. If implementation of this is too costly, time consuming or impossible, then the region can be selected by use of coordinates, in the same manner as done at iiif.io.

![screen shot 2015-06-22 at 15 55 22](https://cloud.githubusercontent.com/assets/3542255/8283343/22462de6-18f7-11e5-9d22-d10114b39d3f.png)

Selection of a region is designated by the icon
![screen shot 2015-06-22 at 15 54 06](https://cloud.githubusercontent.com/assets/3542255/8283316/ef569182-18f6-11e5-93e5-cc6fd44b9666.png)

**Comment by mzeinstra** [comment]
@Taskamp This needs a new icon, more similar to the crop icon that is often used.

@tomkr The result of select a crop would be an embed similar to:

```
<div class="embdrWrapper" style="position: relative; padding-bottom: 134%; padding-top: 0px; height: 0;">
	<img src="http://iiifhawk.klokantech.com/_90402_RP_T_1887_A_1385/2000,0,1000,1500/1000,1500/0/native.jpg" style="width:100%; height:auto;" />
	<div class="embdrAttribution">
		Title: test <br/>
		Source: Europeana
	</div>
</div>
```

Where padding-bottom equals the w divide by the height of the selection and the selection encoded in the API request. It includes attribution information.

**Comment by mzeinstra** [comment]
We've had a discussion about the UX of this feature.

Steps.

1. User clicks on crop icon
2. Mouse becomes a cross cursor:crosshair, panning is disabled
3. User selects a region that the users wants to embed
4. To discuss (user can reshape boundaries of region)
5. User is presented with embed options:
![hawk_webdesign_selection_embed](https://cloud.githubusercontent.com/assets/5627431/8695823/0b0196ea-2ae8-11e5-915b-e895d75ca1e5.jpg)

**user updates size through dropdown**
When a user updates the size through a dropdown the embedcode will be adjusted as well as the px dimension fields 

**user updates size through px fields**
When a user updates the size through a px field the embedcode will be adjusted. px fields always keep their relative dimensions to avoid stretching of the image.

**user updates rotation**
Rotation options are 0,90,180,270, when updated the embedcoded and preview is updated.

**user click exit cross**
This resets the selection and enables the panning of the image again

**Preview**
Preview always shows the image on the max width of its container, it is not a representation of the chosen size.

**library suggestion**
I believe you can use http://annotorious.github.io/demos/openseadragon-preview.html to make this work.

**Comment by mzeinstra** [comment]
https://github.com/msalsbery/OpenSeadragonImagingHelper cold also be used to build this functionality.

**Comment by tomkr** [comment]
* [ ] Maintain ratio between width and height.

**Comment by mzeinstra** [comment]
Wrap in image tag needs metadata as well. 

```   
<div id="embedr_img">
  <img src>
  <p><title>|<creator with link>|<organisation with link>|<license with URL></p>
</div>
```

**Comment by tomkr** [comment]
We don't have links for the creator.

**Comment by mzeinstra** [comment]
Updated the comment, still needs metadata tags

**Comment by mzeinstra** [comment]
![screen shot 2015-09-16 at 9 18 09](https://cloud.githubusercontent.com/assets/5627431/9898612/e54111ae-5c53-11e5-9a94-6282fcb0e2ce.png)

**Comment by mzeinstra** [comment]
```
<div class="embdr_wrapper" style="position: relative; padding-bottom: 72.55%; padding-top: 0px; height: 0;"><img scr='http://iiif.embedr.eu/moma_45309/full/full/0/native.jpg'>
    <div id="embedr_title">
       details of '<title>' | <creator with link> | <published with link> | <license img><license URL>
    </div>
</div>
```

**Comment by mzeinstra** [comment]
This is issue is done, we'll make separate tickets for finetuning.
