### ISSUE TITLE
Advanced search is not well adjusted

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#52]
To give an example, the Nachtwacht or Militia Company of District II under the Command of Captain Frans Banninck Cocq is in the database. This image is a public domain work (also recognised as such as it says so in the attribution). However, if I try advanced search on non commercial, and I query on eg "rijksmuseum" no results are returned. (If I choose "freely reusable" in the advanced option search and I query on "Rijksmuseum", it does return the nachtwacht)

I'm not sure if this is some mistake in the metadata (I doubt it) or in the way the search engine is constructed or somewhere else.

**Comment by tomkr** [comment]
The search works in line with what is described in #12. The license of the Nachtwacht is http://creativecommons.org/publicdomain/zero/1.0/, which is not part of non commercial in #12, but I guess it should be added?
