### ISSUE TITLE
Once you remove advanced search the website needs to forget its advanced search settings

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#55]
Once you have selected an advanced search and you close the advanced search option the system needs to search on license=* instead or remembering its latest settings. Otherwise there is no option to search the entire catalogue again.

**Comment by tomkr** [comment]
The license is never *, it is freely reusable by default even if the advanced search is never opened. This is in line with ticket #12 where a no-license option was not deemed necessary. The only two options are the ones listed and choosing freely reusable gets you your basic search again.
