### ISSUE TITLE
Copy in javascript not supported?

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#56]
You said that the copy button probably won't work? However I see that the second answer show wide support for javascript copy to clipboard:

https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript

**Comment by tomkr** [comment]
It's not supported on Safari and I have no idea how IE usage is doing. I'd argue against using it, because most people know how to copy, Youtube's embedding doesn't provide a copy button, and clicking a button and nothing happening is much more annoying than not having a button.

**Comment by mzeinstra** [comment]
Clear.
