### ISSUE TITLE
Embed functionality needs to have a secondary option

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#57]
We would like to amend the embed functionality.

![screen shot 2015-09-10 at 17 55 22](https://cloud.githubusercontent.com/assets/5627431/9793308/20de47b8-57e5-11e5-93df-52258dce3045.png)

Instead of only offering one embed option we want to add a secondary option, enabled through a checkbox called 'zoomable'.

If checked the embed code remains as it is.

When unchecked the embedcode changes to a static image

**Comment by tomkr** [comment]
The part with the title will probably look really weird, because it won't have the stylesheets. Is this something I can pick up as overflow, as it's fairly short notice?

**Comment by mzeinstra** [comment]
Confirmed that this can be picked up as overflow.

**Comment by mzeinstra** [comment]
```
<div class="embdr_wrapper" style="position: relative; padding-bottom: 72.55%; padding-top: 0px; height: 0;"><img scr='http://iiif.embedr.eu/moma_45309/full/full/0/native.jpg'>
    <div id="embedr_title">
       details of '<title>' | <creator with link> | <published with link> | <license img><license URL>
    </div>
</div>
```

**Comment by Taskamp** [comment]
To make this clearer, see the design of the checkbox below. 

![f1b6af9c-58a3-11e5-9eef-d2121f5cb338](https://cloud.githubusercontent.com/assets/3542255/10096374/472ce3b0-6371-11e5-8428-7ccaf9005c5f.jpg)

After you've implemented this functionality, please also adjust the design of the popup accordingly, by including the checkbox.

**Comment by mzeinstra** [comment]
We've decided that we want to implement this slightly different.

We want this to be the same/similar embed code but that OpenSeaDragon no longer allows the user to zoom and  pan. The result is an iframe that fills the width of available space on the third party site, that cannot be zoomed in or out. This way we can control its content (and tracker).

The following options need to be removed from the player when this is embedded without zoomfunctionality:
* The + and - button
* The crop functionality

Otherwise it needs to follow the design as outlined above.

**Comment by mzeinstra** [comment]
'make embedded image zoomable'
