### ISSUE TITLE
CSS ids, Classes need to be unique

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#58]
As lots of parts of embedr are going to be embedded on other website we need to avoid embedr taking over arbitrary styling from other sites. Avoid/Change generic id's and classes in css like title.

**Comment by tomkr** [comment]
The embedded bits are iframes, so they shouldn't clash with stylesheets set in the set wrapping it.

**Comment by mzeinstra** [comment]
You are right..
