### ISSUE TITLE
Embedr needs HiDPi icons

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#59]
See title

@Taskamp have all HiDPi icons been delivered to @tomkr ?

**Comment by Taskamp** [comment]
@tomkr which icons do you already have in HiDPi and which ones do you still need?

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/9898510/1c503c70-5c53-11e5-8bed-09366fd24bbb.png)

**Comment by Taskamp** [comment]
The hidpi icons will follow after the review, at the end of next week.

**Comment by tomkr** [comment]
So it's ok for the release to use the current icons?

**Comment by Taskamp** [comment]
Yes, including the 2 I sent you today through dropbox

**Comment by mzeinstra** [comment]
@Taskamp can you check if this has been done?

**Comment by Taskamp** [comment]
It's done. I will not close the issue, because we will provide Tom with the HiDPi in the overflow stage.

**Comment by Taskamp** [comment]
HiDPi icons sent to Tom.
