### ISSUE TITLE
There should be no frame around the iFrame embed

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#62]
When embedding in an iFrame, there is a frame (light blue? line) around the image. This should be invisible. See this image:

![screen shot 2015-09-20 at 15 31 38](https://cloud.githubusercontent.com/assets/3542255/9980969/bee96c74-5fad-11e5-89cb-3f0c2413a1b3.png)

**Comment by mzeinstra** [comment]
That happens when you select the iFrame as if you want to copy it.

**Comment by mzeinstra** [comment]
@Taskamp can this be closed?
