### ISSUE TITLE
Single item page: no way to navigate back to search results

### ISSUE THREAD

**Issue by paul2keller** [tomkr/embedr#63]
once i am on an image page there is no way to navigate back to the list of serach results (i.e te previous page). the back button gets me back to the homepage (if this was the first search of the visit) or to the previous item page (if this was a subsequent search). The back button should take me back to the search results

**Comment by mzeinstra** [comment]
Will not fix this before Thursday, this is complex.

**Comment by tomkr** [comment]
The back button going back to the list of search results is a little complex, since the results are not a real page of their own, but rendered in javascript. A simpler option would be to show the query in the search bar of the viewer page. It can then easily be used to search again from this page. If you can specify which option you would prefer and the requirements I can see what would be the best way to implement this.

**Comment by mzeinstra** [comment]
Most people won't use the search button again an assume it is their browser history, which you can manipulate in html5 (pushstate), adoption is pretty high only missing opera mini and some older browser (max 7% of all users) and/or store the search query in the anchor. 

We want to make it more usable for the end-user, your workaround would not help if you already pressed the back button, but it is a good idea to show the search query in the search bar after search.

**Comment by tomkr** [comment]
Could you give a list of browsers in which this is currently not working. In both Safari and Firefox the back button from the viewer gets me to the search results grid.

**Comment by mzeinstra** [comment]
I don't understand, nothing has changed right? If I go to dev.embedr.eu search for rijksmuseum. select one of the items, get to the viewer page and press back, then I want to see the search results I had before. I don't see them now in for example Chrome.

**Comment by paul2keller** [comment]
for me i get the desired behavior in safari but not in chrome.

**Comment by tomkr** [comment]
* [ ] Implement push state for the searches

**Comment by mzeinstra** [comment]
[ ] with proper encoding

http://dev.embedr.eu/results/Otto%20Obreen/?license=freely
does not work, but 
http://dev.embedr.eu/results/Otto+Obreen/?license=freely
does
also 
http://dev.embedr.eu/results/%22Otto+Obreen%22/?license=freely
gives no results.

**Comment by mzeinstra** [comment]
Als complex queries should give results, like: 
http://dev.embedr.eu/results/institution:*museum*%20title:*kom/?license=freely

**Comment by tomkr** [comment]
It uses a query string param now that is encoded. It works for the use cases you provided, try some more to see if it breaks. :8ball:

**Comment by mzeinstra** [comment]
http://dev.embedr.eu/results/?query=*&license=non-commercial does not yield any results.

As longs as you are at the license part. It would be good to make freely reusable the default, that makes nicer URLs, if non-commercial is not set &license should not appear.

I think we should have a default license

**Comment by tomkr** [comment]
The omission of the license=freely is available for testing on dev.embedr.eu.

**Comment by mzeinstra** [comment]
The non-commercial license search is broken due to my mistake in my ingestion script. It omitted non-commercial licenses.

Another item I do see is failing is searches that are not covered also do not receive a result back:

http://dev.embedr.eu/results/?query=wrongfacet%3A*

I expect either 'Incorrect Query.' I prefer the latter

**Comment by tomkr** [comment]
Can be tested on http://dev.embedr.eu/results/?query=wrongfacet%3A*

**Comment by mzeinstra** [comment]
Seems to be in order. Closing.
