### ISSUE TITLE
Embed buttons disappear when the curser hovers over the embed box

### ISSUE THREAD

**Issue by paul2keller** [tomkr/embedr#64]
After i have opened an ebend box (either via the normal embed or via the selection tool) the embed buttons will disappear whenever the cursor hovers over the embed-box. (move cursor away from embed box and then back over the embed box to reproduce). this behaviour is present on both safari & chrome

**Comment by mzeinstra** [comment]
This is going to be difficult to fix before Thursday. I don't have the technical capabilities and time to understand how this works in javascript.

**Comment by mzeinstra** [comment]
https://github.com/tomkr/embedr/blob/master/app/scripts/viewer.js

**Comment by mzeinstra** [comment]
This is fixed. @paul2keller can you confirm? http://dev.embedr.eu/europeana___2058810__UBB__5564c590e290528bba29b7b1e1beb418__artifact__cho/

**Comment by paul2keller** [comment]
yes the issue has been resolved. (the buttons still dissapear if you are moving the cursor over the black bar at the top of the image, but i think that is intentional behaviour (makes sense if there is no embed box present, but looks a bit silly if the box is there). guess this is something that we need to look at at a leter stage
