### ISSUE TITLE
license icon does not show up when doing selection embed

### ISSUE THREAD

**Issue by paul2keller** [tomkr/embedr#66]
the link to the license icon image file in the metadata section of selection embeds is broken. the embedded link points to /static/img/pd.png (this needs to be a full URL pointing to a ressource on embedr.eu

**Comment by mzeinstra** [comment]
Can you give a screenshot of this? Does this happen at the embed or at a static embed? etc.

**Comment by paul2keller** [comment]
<img width="536" alt="screen shot 2015-09-21 at 10 47 12" src="https://cloud.githubusercontent.com/assets/5593766/9988127/2636a2de-604e-11e5-9c62-520cef5b2316.png">

as it says in the title this happens when  doing a selection embed (you can clearly see the non working URL in the code that is diplayed in the form):

<img width="434" alt="screen shot 2015-09-21 at 10 48 37" src="https://cloud.githubusercontent.com/assets/5593766/9988147/5d5f33a2-604e-11e5-8e01-840feda1015f.png">

**Comment by mzeinstra** [comment]
Fixed in: https://github.com/tomkr/embedr/commit/e304fbb46b0e4fd306d14025515b9fac448812b7 needs a pull request to Klokan Technologies

**Comment by mzeinstra** [comment]
This has been fixed.
