### ISSUE TITLE
Metadata needs always have values 

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#68]
There are no checks if data exists at: https://github.com/tomkr/embedr/blob/e304fbb46b0e4fd306d14025515b9fac448812b7/app/scripts/components/viewer.jsx#L34

this causes ugly effects in the title bar in the bottom of the viewer:

![screen shot 2015-09-22 at 14 20 50](https://cloud.githubusercontent.com/assets/5627431/10018207/265f72e4-6135-11e5-97de-15d5be5ecbaf.png)

This needs to follow the rules set out in: https://github.com/tomkr/embedr/issues/7#issuecomment-119548981

**Comment by mzeinstra** [comment]
![screen shot 2015-09-22 at 18 13 05](https://cloud.githubusercontent.com/assets/5627431/10024057/9766b1d0-6155-11e5-9ca0-26acffd28ce2.png)

Good implementation, just needs to be lowercase. 'unknown' and creator unknown as per #7

**Comment by Taskamp** [comment]
A ' (apostrophe) is not recognised, and the result looks ugly. 

![screen shot 2015-09-25 at 10 05 40](https://cloud.githubusercontent.com/assets/3542255/10095861/23833224-636d-11e5-9352-530b8fca3d36.png)

**Comment by mzeinstra** [comment]
@Taskamp this is an issue with our ingestion, not the presentation I believe. Would also needs its own ticket
