### ISSUE TITLE
Collect css and place in theme directory

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#69]
The websites main css template is hosted at /styles/main.css this should be in the wordpress template directory.

**Comment by tomkr** [comment]
Is there a solid reason to do this? My current setup allows me more freedom to re-use css between the application components and Wordpress. Splitting them up seems to me to be spending time for no real gain.

**Comment by mzeinstra** [comment]
It is a vulnerability when updating wordpress imo.

**Comment by mzeinstra** [comment]
@tomkr what happens now when you push a new version to production, does it also overwrite the current WP install? 

Perhaps you should remove the entire WP install and keep only the theme and other customised parts.

**Comment by tomkr** [comment]
Pushing a new version overrides the entire WP directory. I have done this to ensure that we have WP in version control, which means we can control when and what we change and go back on previous changes. This doesn't mesh well with the default WP upgrade path, but upgrading a key piece of software directly on your production server seems like a huge mistake anyway.

**Comment by mzeinstra** [comment]
The has repo has been substantially been cleaned, solving this issue.
