### ISSUE TITLE
Add Metadata information box

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#7]
Metadata can be found under the icon 
![screen shot 2015-06-22 at 15 39 37](https://cloud.githubusercontent.com/assets/3542255/8283655/cc23dbaa-18f8-11e5-921d-4d5677f41c1d.png)

The metadata that should be displayed is:
- Title (title of the work)
- Creator (name of the creator)
- Institution (name of the institution)
- License (link to the license)
- Description (metadata - further description about the image)

I will let our designer make the design for the metadata field.

- [x] @Taskamp will provide a design of the metadata fields
- [ ] @tomkr will implement the design

**Comment by Taskamp** [comment]
The metadata should appear below the picture, in a similar way as displayed here: 

![screen shot 2015-07-06 at 14 12 00](https://cloud.githubusercontent.com/assets/3542255/8522016/171b2ff4-23ea-11e5-81eb-99e712aadd8c.png)

The font is Raleway, and the Creative Commons icon directs you to the CC-page that explains this license. 

The icons can be downloaded at this page:

https://creativecommons.org/about/downloads

The information that we include in the metadata are:

Title of the work, Creator, Institution and license. You can leave out the description.

**Comment by tomkr** [comment]
@Taskamp Will this box always be visible or can it be toggled on and off?

**Comment by mzeinstra** [comment]
We will come back on with a final design description, in the meantime we have hacked this Flask templating for displaying this metadata consistently. 

```
<div id="title">
	{% if item.title %}
		{{ item.title }}
	{% else %}
		Untitled
	{% endif %} 
	{% if item.creator %}
		({{ item.creator }})
	{% else %}
		(creator unknown)
	{% endif %}
	–
	{% if item.source %}
		<a href="{{ item.source }}">{{ item.institution }}</a>
	{% else %}
		{{ item.institution }}
	{% endif %}
	–
	<img src=http://mirrors.creativecommons.org/presskit/icons/cc.png />
	{% if "publicdomain" in item.license %}
		<a href="{{ item.license }}">No rights reserved.</a>
	{% else %}
		<a href="{{ item.license }}">Some rights reserved.</a>
	{% endif %}
 </div>
```

When all information is available it shows (pseudocode):
```
Title (Creator)
<a source>institution</a> – <a license>Some rights reserved.</a>
```

* it shows 'creator unknown' when item.creator is empty
* it shows 'Untitled' when item.title is empty
* it removes the link of institution when not available

I don't know if Flask can do that final comparison {% if "publicdomain" in item.license %} else we should solely go for <a href="{{ item.license }}">Some rights reserved.</a>

**Comment by tomkr** [comment]
Created a new PR for this in https://github.com/klokantech/hawk/pull/49. Includes your Flask code verbatim @mzeinstra. :smile_cat:

**Comment by mookl** [comment]
* infobalk onderin is niet conform design (zie boven): balk moet 34px hoog zijn, font Unbuntu Regular size:14px. CC-icon moet veel kleiner zodat het mooi in de balk van 34px past. 
* Maker en Institution moeten ook links worden.

**Comment by mzeinstra** [comment]
Ook zie ik een achtergrond en een transparante laag, graag alleen de niet doorzichtbare achtergrond kleur:

![screen shot 2015-07-08 at 13 36 55](https://cloud.githubusercontent.com/assets/5627431/8569411/b137282a-2577-11e5-8aa1-2d6393f15019.png)

Gezien de Flask templating werkt zou ik graag de volgende aanpassing nog willen doorvoeren:

```
      {% if item.title %}
        {{ item.title }}
      {% else %}
          untitled
      {% endif %}
      |
      {% if item.creator %}
          {{ item.creator }}
      {% else %}
          creator unknown
      {% endif %}
      |
      {% if item.source %}
          <a href="{{ item.source }}">{{ item.institution }}</a>
      {% else %}
          {{ item.institution }}
      {% endif %}
      |
      {% if "publicdomain" in item.license %}
          <img src=https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Cc-pd.svg/64px-Cc-pd.svg.png />
          <a href="{{ item.license }}">No rights reserved.</a>
      {% else %}
          <img src=http://mirrors.creativecommons.org/presskit/icons/cc.png />
          <a href="{{ item.license }}">Some rights reserved.</a>
      {% endif %}
```
Waar de img's lokaal staan ipv gehotlinked worden.

**Comment by tomkr** [comment]
* De transparante balk is het gevolg van het grote icoontje, dus dat is zo op te lossen.
* Waar moet de creator naar linken? Die link zit niet in het template.
* Aanhalingstekens zal ik toevoegen.

**Comment by mzeinstra** [comment]
Maker heeft geen link, dat had Marcel verkeerd begrepen. 
Ik heb mijn Flask geupdatet met de aanhalingstekens bij de titel van het werk.

**Comment by tomkr** [comment]
@mzeinstra Volgens mij zou deze inmiddels goed moeten zijn.

**Comment by mzeinstra** [comment]
Yes, seems ok.

**Comment by Taskamp** [comment]
New design will come tomorrow. The metadata box will be black again.

**Comment by mookl** [comment]
New design for metadatabox + new close icon. 
Font: Ubuntu 12

![embedr_photopage](https://cloud.githubusercontent.com/assets/13234593/9327138/f36b3622-459e-11e5-8bc1-144573bc3600.jpg)

**Comment by tomkr** [comment]
@Taskamp @mzeinstra Is the metadata box openable and closable now? It isn't that way now. Also can the license logo's be made available in this color scheme?

**Comment by mookl** [comment]
New icons (quite difficult to read at this size, but we can make improvements later optionally).

![pd-icon-inverted](https://cloud.githubusercontent.com/assets/13234593/9327972/e5ad77c4-45a4-11e5-8a67-2cc644fabb23.png)
![cc-icon-inverted](https://cloud.githubusercontent.com/assets/13234593/9327973/e5ada6cc-45a4-11e5-9664-561152dcf870.png)

**Comment by mzeinstra** [comment]
The close button is a one time hiding of the metadata. It is their by default but can be hidden by a user action. Once hidden it cannot be un-hidden.

**Comment by tomkr** [comment]
@mzeinstra Could you provide the close button (both dark and light backgrounds)?

**Comment by mzeinstra** [comment]
@Taskamp indicated in the call that she would provide you with this.
