### ISSUE TITLE
Mouse keeps focus problems

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#79]
Probably needs to be solved by the people of OpenSeaDragon. See https://github.com/openseadragon/openseadragon/issues/697 

It is a problem that is inherent to the iFrame. The problem does not occur when loading the viewer without an iFrame.

**Comment by mzeinstra** [comment]
The OSD thread referenced above has a work-around.

**Comment by mzeinstra** [comment]
We should either implement the work-around in our copy of OSD or have OSD update their repository. I don't know which route to take an would like your advise/implementation on this.

**Comment by tomkr** [comment]
That depends on our timeframe. We can implement the workaround whenever we want, otherwise we're dependent on a new release of OSD. Of course we do both as well, update now and then pull in an updated OSD later. If they decide it needs a fix in the first place.

**Comment by tomkr** [comment]
It looks like this might best be fixed in the hawk-part of the app, since that is the OSD implementation that is used in the viewer.

**Comment by tomkr** [comment]
* [ ] Hotfix OSD according to the named issue and put it in hawk.

**Comment by tomkr** [comment]
I made the change to OSD. It makes some tests fail there, so it seems like it's a bit of a hack. However it does work for me. Of course this needs to be integrated on the hawk side to have an effect. And the newer OSD version breaks some things there.

You can see it at https://github.com/tomkr/openseadragon/tree/iframe-zoom-fix

**Comment by mzeinstra** [comment]
Looks fine to me.
