### ISSUE TITLE
Crop functionality should never default to original pixel size.

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#84]
Crop functionality refers to the original pixel size. This can cause problems in the future if we want raise our max pixel size. 
![screen shot 2015-10-29 at 12 06 57](https://cloud.githubusercontent.com/assets/5627431/10816756/959a13b8-7e35-11e5-8ad7-ee72bb2cb82e.png)

```
<div id='embedr_img'><img src='http://iiif.embedr.eu/Privat-Livemont_-_Absinthe_Robette_-_1896_-_Original_tif/787,2087,6949,6024/6949,6024/0/native.jpg'/><p>Detail of 'Absinthe Robette (1896)' | Henri Privat-Livemont (1861-1936) | <a href='http://www.loc.gov/' target='_blank'>Library of Congress</a> | <img src='http://media.embedr.eu/static/img/pd.png' /> <a href='https://creativecommons.org/publicdomain/mark/1.0/'>No rights reserved.</a></p></div>
```
```
http://iiif.embedr.eu/Privat-Livemont_-_Absinthe_Robette_-_1896_-_Original_tif/787,2087,6949,6024/6949,6024/0/native.jpg
```
should be max
```
http://iiif.embedr.eu/Privat-Livemont_-_Absinthe_Robette_-_1896_-_Original_tif/787,2087,6949,6024/!2056/0/native.jpg
```
or
```
http://iiif.embedr.eu/Privat-Livemont_-_Absinthe_Robette_-_1896_-_Original_tif/787,2087,6949,6024/,!2056/0/native.jpg
```
depending on it orientation.

To solve this ticket let's make 1000px the standard max width of height, depending on which is higher.

See https://github.com/klokantech/hawk/issues/66#issuecomment-151851265

**Comment by tomkr** [comment]
* [ ] Default crop size should be maximised

Maximum is currently 2056. You want this to be 1000?

**Comment by tomkr** [comment]
* [ ] Max is 1000 on first embed
* [ ] Max is 2056 when manually editing
