### ISSUE TITLE
dev.embedr.eu online

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#9]
dev.embedr.eu is where we are going to test the implementation of the front-end of the work. @tomkr will install a wordpress site and his front-end code.

**Comment by mzeinstra** [comment]
This includes one theme page that allows you to create pages and update pages using the following design guidelines. 


![hawk_webdesign_text_picture](https://cloud.githubusercontent.com/assets/5627431/8287153/1479a4ec-190e-11e5-85c4-2ca08e1db4a2.jpg)

![hawk_webdesign_text](https://cloud.githubusercontent.com/assets/5627431/8287155/1b1decae-190e-11e5-92f4-1d3d27b3070e.jpg)

**Comment by tomkr** [comment]
@mzeinstra The initial version of dev.embedr.eu is now live. It's still work in progress, but I will regularly post new builds there now so the progress can be checked.

**Comment by tomkr** [comment]
There is an about page on http://dev.embedr.eu/about/. I will give you credentials to the the wordpress instance. Please let me know what other pages will be needed, as for now they are hardcoded into the search engine's menu.

**Comment by mzeinstra** [comment]
Please provide credentials for mz@kl.nl and tas@kl.nl

**Comment by tomkr** [comment]
Both of you should have received mail. :smile:
