### ISSUE TITLE
Viewer page removed on dev.embedr.eu

### ISSUE THREAD

**Issue by tomkr** [tomkr/embedr#92]
I can't seem to access the viewer page on dev.embedr.eu. It was removed from the list of pages, and I recreated it, but this seems to have generated a viewer-2 slug, which doesn't work. Is there something you can do?

**Comment by mzeinstra** [comment]
I've restored it from the trash, works now?

**Comment by tomkr** [comment]
As we discussed, there seems to be some weird caching going on on the dev server. I don't think this used to be the case. Can you check what is going on?

**Comment by mzeinstra** [comment]
Acting as a sys-admin. Closing this issue. Will no fix, is a feature not a bug. 

That's not how the internet works  ;)
