### ISSUE TITLE
?nozoom=1 viewer should also not be panable

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#94]
The ?nozoom=1 viewer now allows panning of the image, this needs to be disable

* [x] ?nozoom=1 viewer need to disallow horizontal panning
* [x] ?nozoom=1 viewer need to disallow vertical panning

**Comment by tomkr** [comment]
Available for testing on http://dev.embedr.eu/viewer/?nozoom=1.

**Comment by mzeinstra** [comment]
Can't pan! :)
