### ISSUE TITLE
Header is no longer visible on content pages

### ISSUE THREAD

**Issue by mzeinstra** [tomkr/embedr#96]
I can't see the search functionality anymore on content pages:
http://dev.embedr.eu/content/contact/

![screen shot 2015-11-26 at 14 53 59](https://cloud.githubusercontent.com/assets/5627431/11424446/90b37424-944d-11e5-8eba-de24de3450ca.png)

**Comment by tomkr** [comment]
Can be tested on http://dev.embedr.eu/content/contact/

**Comment by mzeinstra** [comment]
Problem solved.
